### ISSUE TITLE
simplekv 0.11.1 breaks flask-kvsession 0.6.2 on Python 2.7

### ISSUE THREAD

**Issue by karteek** [mbr/simplekv#57] opened 2017-09-13 15:43 UTC
simplekv 0.11.1 breaks flask-kvsession 0.6.2
sid_s created by kvsession is of type `str` rather than the expected type `unicode`

```
Traceback (most recent call last):
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/flask_kvsession/__init__.py", line 193, in save_session
    store.put(session.sid_s, data, ttl)
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/simplekv/decorator.py", line 73, in put
    self._dstore.put(self._map_key(key), *args, **kwargs))
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/simplekv/decorator.py", line 104, in _map_key
    self._check_valid_key(key)
  File "/opt/my-flask-app/ENV/local/lib/python2.7/site-packages/simplekv/__init__.py", line 190, in _check_valid_key
    raise ValueError('%r is not a unicode string' % key)
```

**Comment by hachreak** [comment] 2017-09-14 06:36
Same issue on Invenio and [derivated](https://github.com/inspirehep/inspire-next/pull/2744)! :+1:

**Comment by fmarczin** [comment] 2017-09-14 10:01
With 0.11, simplekv became more strict in what it accepts as keys, maybe too strict. Will look into it.

**Comment by mbr** [comment] 2017-09-14 10:45
Backwards compatibility is fairly important, especially for flask-kvsession. If this is a somewhat simple fix, we could do another release. If not, I'll have to pin flask-kvsession to a specific version.

**Comment by fmarczin** [comment] 2017-09-14 11:38
@mbr I agree this should be fixed ASAP. 

At least in part, this seems like a design decision to me. Should simplekv be strict about requiring a unicode type for keys or not, ie. accept bytestrings as long as they can be cast to valid keys. 

What's your take? Based on that, I'm prepared to make a new release that implements/fixes this.

**Comment by mbr** [comment] 2017-09-14 16:26
Here's a little summary, just to make sure I understand the issue correctly:

> At least in part, this seems like a design decision to me. Should simplekv be strict about requiring a unicode type for keys or not, ie. accept bytestrings as long as they can be cast to valid keys.
> 
> What's your take? Based on that, I'm prepared to make a new release that implements/fixes this.

I had to retcon that a bit, since the adoption of Python3 and the stricter distinction between strings and unicode objects happened through its development.

As a general rule (hopefully I'm not contradicting myself here), keys should always be unicode strings, even if they restricted by the following constraint (from the docs):

> Keys are ascii-strings with certain restrictions, guaranteed to be properly handled up to a length of at least 250 characters. Any function that takes a key as an argument raises a ValueError if the key is incorrect.

Values should always be bytestrings.

That leaves the not-even-edge-case of passing `b'foo'` as a key value. Any valid bytestring should be decodeable using the ASCII codec, so it's up to us to decide whether or not to reject them or silently convert them.

If I wrote `simplekv` today, I would simply reject non-unicode values with a `ValueError` or `TypeError`. It would also be Python3 only!

However, there is a lot to be said for backwards compatibility. Python3 makes this, unfortunately a bit harder than Python2. Compare:

Py2:

```py
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 'aasdf'.decode('ascii')
u'aasdf'
>>> u'aasdf'.decode('ascii')
u'aasdf'
```

Py3:

```py
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'aasdf'.decode('ascii')
'aasdf'
>>> 'aasdf'.decode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'
```

I think I would prefer to not break all the existing software for no good reason and simply add a cast/conversion.

**Comment by mbr** [comment] 2017-09-14 16:32
Is there any fast, built-in funciton that does this type of cooercion? We may need some sort of helper, like (caution, raw pseudo-python):

```py
if PY2:
    force_unicode = str
else:
    def force_unicode(raw):
         return str(raw, 'ascii')
```

Any better solution much appreciated

**Comment by fmarczin** [comment] 2017-09-14 16:53
Would you suggest to cast every `str` key on PY2 to `unicode` from each method in the public API, analogous to calling `_check_valid_key()`?

Or should we just do it like in earlier versions and pass the key to the backend unchanged, but simply allow `str` (or `basestring`) in `_check_valid_key()` on PY2?

**Comment by fmarczin** [comment] 2017-09-19 08:36
@mbr Would you be ok with going back to the old behaviour of not caring if keys are `str` or `unicode` on PY2 and just checking if it is a `basestring`, that is, #59 as it is?

Or should we do a coercion `str`->`unicode` on PY2, `bytes`->`str` on PY3?

**Comment by mbr** [comment] 2017-09-21 09:22
> @mbr Would you be ok with going back to the old behaviour of not caring if keys are str or unicode on PY2 and just checking if it is a basestring, that is, #59 as it is?

I'd fine with that. The issue is, we're not gaining anything at the moment - if we break backwards compat, it should be for a reason.

> Or should we do a coercion str->unicode on PY2, bytes->str on PY3?

I wonder how widely that would be supported. It has the drawback of a little overhead, but makes it simpler for the underlying backend. I would guess that this'd break code that relies on the backend handling the un-coerced keys transparently. Any valid key that passes the regex is a valid ascii string though, so in theory this should never fail?

**Closed** 2017-09-21 11:24 UTC

**Comment by hachreak** [comment] 2017-09-21 12:12
Hi @mbr, could you please release a `0.11.2` version?
Then, also `flask-kvsession` can update minimum requirements.
Thanks

**Comment by fmarczin** [comment] 2017-09-21 12:30
@hachreak @mbr I'm in the process of making a 0.11.2 release

**Comment by hachreak** [comment] 2017-09-21 12:31
@fmarczin cool! thanks :smile:

**Comment by fmarczin** [comment] 2017-09-21 12:48
@hachreak 0.11.2 is out. Give it a try and tell me if the problem has gone away for you.

**Comment by fmarczin** [comment] 2017-09-21 12:58
@mbr One thing that works in our favour is that `'mykey' == u'mykey`, and also `'mykey' in [u'mykey', ...] == True` on Python 2. So coercing `str` to `unicode` should not be as breaking.
Also, I'm not even sure that the current backends always guarantee to give you back the same type that you put in. I know the old memcached backend did not.

**Comment by hachreak** [comment] 2017-09-21 15:07
@fmarczin with `0.11.2` it looks working! :smile:

**Comment by SpootDev** [comment] 2017-09-21 19:50
Thank you!
